# Generated by Django 4.2.6 on 2023-11-29 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.companies'),
        ),
    ]
