# Generated by Django 4.2.6 on 2023-11-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('utils', '0003_costumers_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Costumer',
                'verbose_name_plural': 'Costumers',
            },
        ),
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
        migrations.DeleteModel(
            name='Costumers',
        ),
        migrations.AddField(
            model_name='costumer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.company'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
